services:

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=brekke
      - POSTGRES_PASSWORD=brekke
      - POSTGRES_DB=brekke